package exception_handling;

public class exceptionName {
public static void main(String[] args) 
	{
try 
{
	int c=1/1;
	System.out.println(c);
}
catch(Exception a1)
{
System.out.println("i have handled one exception called AE");
}
	}
}
